### ISSUE TITLE
uninitialized constant MapKit::ZoomLevel

### ISSUE THREAD

**Issue by zxiest** [weibel/MapKitWrapper#5]
Hello =)

I'm getting `uninitialized constant MapKit::ZoomLevel ` . Are there any dependencies I'm missing?

**Comment by weibel** [comment]
I simply would not know. The project worked 2 years ago but I have not updated it since then nor am I planning to do so. RubyMotion has seen massive development during that time, so I think the only course of action is to tinker a bit with the code to get it running. IMHO I think you should find a newer well kept library :-) If you want to work on it I can transfer the github ownership to you.

**Comment by zxiest** [comment]
Thanks for the quick response =) I need to get the library working for me first. I'll let you know if I'd like to manage the repo :-)
